eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    appname: api-gateway
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10



server:
  port: 8215